name: SimpleUndineMailerGUI
version: '${version}'
main: com.gmail.necnionch.myplugin.simpleundinemailergui.bukkit.MailGUIPlugin
api-version: 1.13
depend: [ UndineMailer ]
softdepend: [ LOInfoGUI, floodgate ]
authors: [ Necnion8 ]

description: |-
  UndineMailerのGUIプラグイン
  チャットテキストのクリックに対応しない古いバージョンや統合版向け

commands:
  undinemailergui:
    aliases: [umailgui, mailgui]
    permission: simpleundinemailergui.command.mailgui

permissions:
  simpleundinemailergui.command.mailgui:
    default: true
